### ISSUE TITLE
Embedding in more than 2 dimensions

### ISSUE THREAD

**Issue by scottgigante** [jxz12/s_gd2#12]
Not in any way urgent but it would be nice if we could embed in more than 2 dimensions, especially for 3D visualizations. Thanks so much for this great package!

**Comment by jxz12** [comment]
This was pretty simple to add so I've added a parameter to the mds_direct function to do it. I haven't added it for graphs because the draw_svg and draw_png functions can't handle 3d anyway, so I will leave it to future work. Here's the result on a slightly modified version of the script you shared a while ago:

![3d](https://user-images.githubusercontent.com/13380149/70152388-0820be80-16a5-11ea-800e-cb767feb32c4.png)

Thank you again for your assistance and I hope this is useful for your package as well!

**Comment by scottgigante** [comment]
Thanks so much for the quick work! Extremely helpful for my package :)
